{
    "name": "Tommasi Sales Reactivation",
    "version": "15.0.1.5.0",
    "category": "Sales/CRM",
    "summary": "Configuration and CRM foundation for the sales reactivation agent",
    "author": "Eynes SRL",
    "license": "LGPL-3",
    "website": "https://gitlab.e-mips.com.ar/tommasi",
    "depends": [
        "base",
        "mail",
        "crm",
        "sale",
        "sale_crm",
        "sale_management",
        "stock",
        "product",
        "account",
        "llm_tool",
        "llm_mcp_server",
        "tommasi_custom",
    ],
    "data": [
        "security/reactivation_security.xml",
        "security/ir.model.access.csv",
        "data/crm_stages.xml",
        "data/reactivation_config_data.xml",
        "data/reactivation_sequence.xml",
        "data/reactivation_cron.xml",
        "data/multicompany_demo_backfill.xml",
        "views/tommasi_reactivation_config_views.xml",
        "views/tommasi_reactivation_facts_snapshot_views.xml",
        "views/crm_lead_views.xml",
        "views/tommasi_reactivation_menu.xml",
        "views/tommasi_whatsapp_config_views.xml",
        "views/tommasi_whatsapp_menu.xml",
    ],
    "demo": [
        "data/demo/demo_companies.xml",
        "data/demo/demo_users.xml",
        "data/demo/demo_products.xml",
        "data/demo/demo_customers.xml",
        "data/demo/demo_stock.xml",
        "data/demo/demo_crm_opportunities.xml",
        "data/demo/demo_transactions.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
