from . import test_crm_lead
from . import test_demo_scenario_data
from . import test_reactivation_config
from . import test_reactivation_multicompany
from . import test_reactivation_security
from . import test_reactivation_candidates
from . import test_reactivation_bootstrap_detection
from . import test_reactivation_recommendations
from . import test_reactivation_rendering
from . import test_reactivation_star_products
from . import test_reactivation_crm_create
from . import test_reactivation_batch
from . import test_reactivation_create_safety
from . import test_reactivation_snapshot
from . import test_mcp_transport_contract
from . import test_reactivation_whatsapp
