from . import crm_lead
from . import res_users
from . import ir_rule
from . import tommasi_reactivation_config
from . import tommasi_reactivation_demo
from . import tommasi_reactivation_priority_rule
from . import tommasi_reactivation_seller
from . import tommasi_reactivation_service
from . import tommasi_reactivation_facts_snapshot
from . import service_sellers
from . import service_products
from . import service_facts
from . import service_snapshot
from . import service_bootstrap
from . import service_detection
from . import service_candidates
from . import service_recommendations
from . import service_rendering
from . import service_create_guards
from . import service_opportunities
from . import tommasi_whatsapp_config
from . import tommasi_whatsapp_log
from . import service_whatsapp
