import logging
from datetime import timedelta

from odoo import api, fields, models

_logger = logging.getLogger(__name__)


class CrmLead(models.Model):
    _inherit = "crm.lead"

    reactivation_source = fields.Char(
        string="Reactivation source",
        default="Agente Comercial",
        index=True,
        help="How this reactivation opportunity was created.",
    )
    reactivation_attribution_id = fields.Char(
        string="Reactivation attribution ID",
        index=True,
        copy=False,
        help=(
            "Unique reference assigned to each agent-created reactivation "
            "opportunity."
        ),
    )
    reactivation_is_agent = fields.Boolean(
        string="Agent reactivation",
        default=False,
        index=True,
        help=(
            "Checked when this opportunity was created by the sales "
            "reactivation agent."
        ),
    )
    reactivation_trigger_type = fields.Selection(
        selection=[
            ("inactivity", "Inactivity"),
            ("revenue_decline", "Revenue decline"),
            ("volume_decline_with_stock", "Volume decline with stock"),
            ("dropoff", "Purchase drop-off"),
            ("undelivered_so_lines", "Undelivered sales orders"),
            ("multi", "Multiple triggers"),
        ],
        string="Reactivation trigger type",
        index=True,
        help=(
            "Main reason the customer was flagged, such as inactivity or "
            "a drop in sales."
        ),
    )
    reactivation_confidence = fields.Float(
        string="Reactivation confidence",
        help=(
            "Agent confidence score from 0 to 1 that this customer is worth "
            "reactivating."
        ),
    )
    reactivation_cycle_id = fields.Char(
        string="Reactivation cycle ID",
        index=True,
        help="Identifier of the detection run that created this opportunity.",
    )
    reactivation_operation_key = fields.Char(
        string="Reactivation operation key",
        index=True,
        copy=False,
        help=(
            "Stable idempotency key for agent-created opportunities "
            "(cycle + seller + customer)."
        ),
    )
    reactivation_client_message = fields.Text(
        string="Reactivation client message",
        help=(
            "Ready-to-send message for the customer, generated by the "
            "agent. The seller can copy or forward it."
        ),
    )
    reactivation_contacted_at = fields.Datetime(
        string="Reactivation contacted at",
        help=("Date and time when the opportunity moved to Customer " "contacted."),
    )

    _sql_constraints = [
        (
            "unique_reactivation_attribution_id",
            "unique(reactivation_attribution_id)",
            "Reactivation attribution ID must be unique.",
        ),
        (
            "unique_reactivation_operation_key",
            "unique(reactivation_operation_key)",
            "Reactivation operation key must be unique.",
        ),
    ]

    @api.model
    def cron_archive_stale_pendiente_revision(self):
        """Archive opportunities stuck in Pending review past the config window."""
        stage = self.env.ref(
            "tommasi_sales_reactivation.stage_pendiente_revision",
            raise_if_not_found=False,
        )
        if not stage:
            return

        Config = self.env["tommasi.reactivation.config"]
        configs = Config.search([("active", "=", True)])
        for config in configs:
            days = config.pending_review_archive_days
            cutoff = fields.Datetime.now() - timedelta(days=days)
            leads = self.search(
                [
                    ("stage_id", "=", stage.id),
                    ("company_id", "=", config.company_id.id),
                    ("create_date", "<=", cutoff),
                ]
            )
            if not leads:
                continue
            leads.action_archive()
            _logger.info(
                "Archived %s stale Pending review opportunities for company %s "
                "(older than %s days)",
                len(leads),
                config.company_id.display_name,
                days,
            )
